import { StyleSheet } from "react-native";
import type { ThemeColors } from "../../../context/ThemeContext";

export const makeHomeStyle = (c: ThemeColors) => StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: c.backgroundSecondary,
    padding: 20,
    paddingBottom: 36,
  },
  containerCenter: {
    flex: 1,
    backgroundColor: c.backgroundSecondary,
    alignItems: "center",
    justifyContent: "center",
    padding: 20,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
    marginBottom: 16,
    gap: 12,
  },
  avatar: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: c.primary,
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: { color: "#fff", fontSize: 18, fontWeight: "bold" },
  greetingBlock: { flex: 1 },
  greeting: { fontSize: 13, color: c.textSecondary, fontWeight: "500" },
  welcomeName: { fontSize: 22, fontWeight: "bold", color: c.textPrimary, marginTop: 1 },
  eyeBtn: { backgroundColor: c.eyeBtn, paddingHorizontal: 13, paddingVertical: 7, borderRadius: 20 },
  eyeText: { fontWeight: "600", color: c.textPrimary, fontSize: 12 },
  pageTitle: { fontSize: 22, fontWeight: "bold", color: c.textPrimary, marginTop: 20 },
  pageSubtitle: { fontSize: 13, color: c.textSecondary, marginTop: 2 },
  welcome: { fontSize: 12, color: c.textSecondary },
  welcomeSub: { fontSize: 11, color: c.textSecondary, marginTop: 2 },
  grid: { gap: 12 },
  heroCard: {
    backgroundColor: c.heroCard,
    borderRadius: 18,
    padding: 24,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.22,
    shadowRadius: 14,
    elevation: 8,
  },
  heroDecor1: {
    position: "absolute",
    width: 150,
    height: 150,
    borderRadius: 75,
    backgroundColor: "rgba(255,255,255,0.04)",
    top: -50,
    right: -30,
  },
  heroDecor2: {
    position: "absolute",
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "rgba(52,199,89,0.08)",
    bottom: -30,
    right: 24,
  },
  heroLabel: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 1.4,
    marginBottom: 12,
  },
  heroValue: { color: c.primary, fontSize: 36, fontWeight: "bold", letterSpacing: -0.5 },
  row: { flexDirection: "row", gap: 12 },
  cardHalf: {
    flex: 1,
    backgroundColor: c.card,
    borderRadius: 14,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  card: {
    backgroundColor: c.card,
    borderRadius: 14,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  cardFull: {
    backgroundColor: c.card,
    borderRadius: 14,
    padding: 16,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.06,
    shadowRadius: 6,
    elevation: 2,
  },
  cardLabel: {
    color: c.textSecondary,
    fontSize: 11,
    fontWeight: "600",
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  cardValue: { color: c.textPrimary, fontSize: 17, fontWeight: "bold" },
  cardValueGreen: { color: c.primary, fontSize: 17, fontWeight: "bold" },
  hint: { marginTop: 6, color: c.textSecondary, fontSize: 12 },
  sectionTitle: {
    fontSize: 13,
    fontWeight: "bold",
    color: c.textSecondary,
    marginTop: 24,
    marginBottom: 12,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  btn: { paddingVertical: 15, borderRadius: 12, alignItems: "center", justifyContent: "center" },
  btnPrimary: {
    backgroundColor: c.primary,
    marginTop: 8,
    shadowColor: c.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 5,
  },
  btnPrimaryText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
  btnGhost: { marginTop: 10, borderWidth: 1.5, borderColor: c.border, backgroundColor: c.card },
  btnGhostText: { fontWeight: "600", color: c.textPrimary, fontSize: 16 },
  chartCard: {
    backgroundColor: c.card,
    borderRadius: 16,
    padding: 16,
    marginTop: 16,
    shadowColor: "#000",
    shadowOpacity: 0.05,
    shadowRadius: 8,
    elevation: 2,
  },
  badgeLiga: {
    alignSelf: "flex-start",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 4,
  },
  badgeLigaText: { fontSize: 11, fontWeight: "700" as const, color: "#fff" },
  badgePro: {
    alignSelf: "flex-start",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 4,
    backgroundColor: "#007AFF",
  },
  badgeBasic: {
    alignSelf: "flex-start",
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 2,
    marginTop: 4,
    backgroundColor: c.borderLight,
  },
  badgeProText: { fontSize: 11, fontWeight: "700", color: "#fff" },
  badgeBasicText: { fontSize: 11, fontWeight: "700", color: c.textPrimary },
});
