// Mapeamento de nome de liga (ex: "Cobre I") para a imagem da insígnia.
// Os arquivos ficam em assets/insignias/. Para adicionar/trocar uma insígnia,
// basta substituir o PNG correspondente — nenhuma alteração de código necessária.

const insigniaMap: Record<string, ReturnType<typeof require>> = {
  "Cobre I":     require("../../assets/insignias/cobre_I.png"),
  "Cobre II":    require("../../assets/insignias/cobre_II.png"),
  "Cobre III":   require("../../assets/insignias/cobre_III.png"),
  "Cobre IV":    require("../../assets/insignias/cobre_IV.png"),
  "Cobre V":     require("../../assets/insignias/cobre_V.png"),
  "Bronze I":    require("../../assets/insignias/bronze_I.png"),
  "Bronze II":   require("../../assets/insignias/bronze_II.png"),
  "Bronze III":  require("../../assets/insignias/bronze_III.png"),
  "Bronze IV":   require("../../assets/insignias/bronze_IV.png"),
  "Bronze V":    require("../../assets/insignias/bronze_V.png"),
  "Prata I":     require("../../assets/insignias/prata_I.png"),
  "Prata II":    require("../../assets/insignias/prata_II.png"),
  "Prata III":   require("../../assets/insignias/prata_III.png"),
  "Prata IV":    require("../../assets/insignias/prata_IV.png"),
  "Prata V":     require("../../assets/insignias/prata_V.png"),
  "Ouro I":      require("../../assets/insignias/ouro_I.png"),
  "Ouro II":     require("../../assets/insignias/ouro_II.png"),
  "Ouro III":    require("../../assets/insignias/ouro_III.png"),
  "Ouro IV":     require("../../assets/insignias/ouro_IV.png"),
  "Ouro V":      require("../../assets/insignias/ouro_V.png"),
  "Platina I":   require("../../assets/insignias/platina_I.png"),
  "Platina II":  require("../../assets/insignias/platina_II.png"),
  "Platina III": require("../../assets/insignias/platina_III.png"),
  "Platina IV":  require("../../assets/insignias/platina_IV.png"),
  "Platina V":   require("../../assets/insignias/platina_V.png"),
  "Ametista I":   require("../../assets/insignias/ametista_I.png"),
  "Ametista II":  require("../../assets/insignias/ametista_II.png"),
  "Ametista III": require("../../assets/insignias/ametista_III.png"),
  "Ametista IV":  require("../../assets/insignias/ametista_IV.png"),
  "Ametista V":   require("../../assets/insignias/ametista_V.png"),
  "Safira I":    require("../../assets/insignias/safira_I.png"),
  "Safira II":   require("../../assets/insignias/safira_II.png"),
  "Safira III":  require("../../assets/insignias/safira_III.png"),
  "Safira IV":   require("../../assets/insignias/safira_IV.png"),
  "Safira V":    require("../../assets/insignias/safira_V.png"),
  "Esmeralda I":   require("../../assets/insignias/esmeralda_I.png"),
  "Esmeralda II":  require("../../assets/insignias/esmeralda_II.png"),
  "Esmeralda III": require("../../assets/insignias/esmeralda_III.png"),
  "Esmeralda IV":  require("../../assets/insignias/esmeralda_IV.png"),
  "Esmeralda V":   require("../../assets/insignias/esmeralda_V.png"),
  "Rubi I":    require("../../assets/insignias/rubi_I.png"),
  "Rubi II":   require("../../assets/insignias/rubi_II.png"),
  "Rubi III":  require("../../assets/insignias/rubi_III.png"),
  "Rubi IV":   require("../../assets/insignias/rubi_IV.png"),
  "Rubi V":    require("../../assets/insignias/rubi_V.png"),
  "Diamante I":   require("../../assets/insignias/diamante_I.png"),
  "Diamante II":  require("../../assets/insignias/diamante_II.png"),
  "Diamante III": require("../../assets/insignias/diamante_III.png"),
  "Diamante IV":  require("../../assets/insignias/diamante_IV.png"),
  "Diamante V":   require("../../assets/insignias/diamante_V.png"),
};

export default insigniaMap;
